title: Emily Mader
description: Data Science Masters Student at UC Berkeley (MIDS)
theme: jekyll-theme-minimal

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:name/

plugins:
  - jekyll-feed

exclude:
  - README.md
